import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { usePedidoCompleto } from "@/hooks/usePedidos";
import { generarPDFPedido } from "@/utils/pdfGenerator";
const PedidoDetallePopup = ({ id, onClose }) => {
    const { data: pedido, isLoading, error } = usePedidoCompleto(id);
    const handleGenerarPDF = () => {
        if (pedido) {
            generarPDFPedido(pedido);
        }
    };
    if (isLoading)
        return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center z-50", children: _jsx("div", { className: "bg-white rounded-xl p-6 shadow-lg", children: "Cargando pedido..." }) }));
    if (error || !pedido)
        return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-white rounded-xl p-6 shadow-lg text-red-500", children: ["Error al cargar el pedido.", _jsx("button", { onClick: onClose, className: "mt-4 bg-primary-500 text-white px-4 py-2 rounded-lg", children: "Cerrar" })] }) }));
    return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center z-50 p-4", children: _jsxs("div", { className: "bg-primary-100 dark:bg-gray-800 rounded-xl p-4 sm:p-6 w-full max-w-lg shadow-lg overflow-y-auto max-h-[90vh]", children: [_jsxs("h2", { className: "text-lg sm:text-xl font-semibold mb-4 dark:text-white", children: ["Detalle del Pedido ID: #", pedido.idPedido] }), _jsxs("p", { className: "text-sm sm:text-base dark:text-gray-300", children: [_jsx("strong", { children: "Cliente:" }), " ", pedido.nombreCliente] }), _jsxs("p", { className: "text-sm sm:text-base dark:text-gray-300", children: [_jsx("strong", { children: "Telefono:" }), " +", pedido.telefonoCliente] }), _jsxs("p", { className: "text-sm sm:text-base dark:text-gray-300", children: [_jsx("strong", { children: "Fecha:" }), " ", pedido.fecha.split("T")[0].split("-").reverse().join("/")] }), _jsxs("p", { className: "text-sm sm:text-base dark:text-gray-300", children: [_jsx("strong", { children: "Estado:" }), " ", pedido.estado] }), _jsxs("p", { className: "text-sm sm:text-base dark:text-gray-300", children: [_jsx("strong", { children: "Estado de pago:" }), " ", pedido.metodoDePago] }), _jsxs("p", { className: "text-sm sm:text-base dark:text-gray-300", children: [_jsx("strong", { children: "Total:" }), " $ ", pedido.total?.toLocaleString("es-AR", { minimumFractionDigits: 0, maximumFractionDigits: 0 })] }), pedido.detallePedidos?.map((detalle, idx) => (_jsxs("div", { className: "mt-4 border rounded-lg p-3 bg-primary-50 dark:bg-gray-700", children: [_jsxs("h3", { className: "font-semibold text-sm sm:text-base dark:text-white", children: [detalle.nombreTorta, ", ", detalle.tamanoMedida, " "] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("p", { className: "text-sm dark:text-gray-300", children: ["Cantidad: ", detalle.cantidad] }), _jsxs("p", { className: "font-semibold text-right text-sm sm:text-base dark:text-white", children: ["$ ", detalle.totalProducto?.toLocaleString("es-AR", {
                                            minimumFractionDigits: 0,
                                            maximumFractionDigits: 0
                                        })] })] }), detalle.extras?.length > 0 && (_jsxs("ul", { className: "list-disc list-inside text-xs sm:text-sm text-primary-600 dark:text-primary-400", children: [_jsx("p", { className: "font-medium", children: "Extras: " }), detalle.extras.map((e, i) => (_jsxs("li", { children: [e.nombreCostoExtra, " \u00D7 ", e.cantidad, e.nota ? `  "${e.nota}"` : ""] }, i)))] })), detalle.ingredientesExtras?.length > 0 && (_jsxs("ul", { className: "list-disc list-inside text-xs sm:text-sm text-primary-600 dark:text-primary-400", children: [_jsx("p", { className: "font-medium", children: "Ingredientes extras: " }), detalle.ingredientesExtras.map((e, i) => (_jsxs("li", { children: [e.nombreIngrediente, " \u00D7 ", e.cantidad, e.nota ? `  "${e.nota}"` : ""] }, i)))] }))] }, idx))), _jsxs("div", { className: "flex flex-col sm:flex-row justify-end gap-3 mt-6", children: [_jsx("button", { onClick: onClose, className: "w-full sm:w-auto bg-gray-300 dark:bg-gray-600 text-gray-800 dark:text-white px-4 py-2 rounded-lg hover:bg-gray-400 dark:hover:bg-gray-500", children: "Cancelar" }), _jsx("button", { onClick: handleGenerarPDF, className: "w-full sm:w-auto bg-primary-500 text-white px-4 py-2 rounded-lg hover:bg-primary-600", children: "Enviar" })] })] }) }));
};
export default PedidoDetallePopup;
