import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Edit, Trash2 } from 'lucide-react';
const ResponsiveTable = ({ columns, data, onEdit, onDelete, isLoading, emptyMessage = 'No hay datos disponibles', keyExtractor, mobileCardTitle, mobileCardSubtitle, currentPage, totalPages, onPageChange, }) => {
    if (isLoading) {
        return _jsx("div", { className: "p-6 text-center dark:text-gray-400", children: "Cargando..." });
    }
    if (!data?.length) {
        return _jsx("div", { className: "p-6 text-center text-gray-500 dark:text-gray-400", children: emptyMessage });
    }
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "block lg:hidden space-y-4", children: data.map((row) => (_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 space-y-3", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [mobileCardTitle && (_jsx("h3", { className: "font-semibold text-gray-900 dark:text-white truncate", children: mobileCardTitle(row) })), mobileCardSubtitle && (_jsx("p", { className: "text-sm text-gray-600 dark:text-gray-400 truncate", children: mobileCardSubtitle(row) }))] }), _jsxs("div", { className: "flex gap-2 ml-2 flex-shrink-0", children: [onEdit && (_jsx("button", { onClick: () => onEdit(row), className: "p-2 bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-lg hover:bg-blue-200 dark:hover:bg-blue-800 transition", title: "Editar", children: _jsx(Edit, { size: 18 }) })), onDelete && (_jsx("button", { onClick: () => onDelete(row), className: "p-2 bg-red-100 dark:bg-red-900 text-red-600 dark:text-red-300 rounded-lg hover:bg-red-200 dark:hover:bg-red-800 transition", title: "Eliminar", children: _jsx(Trash2, { size: 18 }) }))] })] }), _jsx("div", { className: "space-y-2 pt-2 border-t border-gray-200 dark:border-gray-700", children: columns.map((col) => {
                                // Skip si es la columna de acciones o si no tiene valor
                                if (col.key === 'actions' || !row[col.key])
                                    return null;
                                return (_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("span", { className: "text-xs font-medium text-gray-600 dark:text-gray-400", children: [col.label, ":"] }), _jsx("span", { className: "text-sm text-gray-900 dark:text-white font-medium", children: col.render ? col.render(row[col.key], row) : row[col.key] })] }, col.key));
                            }) })] }, keyExtractor(row)))) }), _jsx("div", { className: "hidden lg:block overflow-x-auto", children: _jsxs("table", { className: "min-w-full text-left text-sm", children: [_jsx("thead", { className: "bg-primary-200 dark:bg-gray-700", children: _jsxs("tr", { children: [columns.map((col) => (_jsx("th", { className: "px-6 py-3 dark:text-gray-200 font-semibold", children: col.label }, col.key))), (onEdit || onDelete) && (_jsx("th", { className: "px-6 py-3 dark:text-gray-200 font-semibold", children: "Acciones" }))] }) }), _jsx("tbody", { children: data.map((row) => (_jsxs("tr", { className: "bg-primary-50 dark:bg-gray-800 border-t dark:border-gray-700 hover:bg-primary-100 dark:hover:bg-gray-750 transition", children: [columns.map((col) => (_jsx("td", { className: "px-6 py-3 dark:text-gray-200", children: col.render ? col.render(row[col.key], row) : row[col.key] }, col.key))), (onEdit || onDelete) && (_jsx("td", { className: "px-6 py-3", children: _jsxs("div", { className: "flex items-center gap-4", children: [onEdit && (_jsx("button", { onClick: () => onEdit(row), className: "text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 transition-colors", title: "Editar", children: _jsx(Edit, { size: 18 }) })), onDelete && (_jsx("button", { onClick: () => onDelete(row), className: "text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 transition-colors", title: "Eliminar", children: _jsx(Trash2, { size: 18 }) }))] }) }))] }, keyExtractor(row)))) })] }) }), currentPage && totalPages && onPageChange && totalPages > 1 && (_jsxs("div", { className: "flex justify-between items-center mt-4 px-2", children: [_jsx("button", { onClick: () => onPageChange(currentPage - 1), disabled: currentPage === 1, className: `px-4 py-2 rounded-md ${currentPage === 1
                            ? 'bg-gray-200 text-gray-400 cursor-not-allowed dark:bg-gray-700 dark:text-gray-500'
                            : 'bg-primary-500 text-white hover:bg-primary-600 dark:bg-primary-600 dark:hover:bg-primary-700'}`, children: "Anterior" }), _jsxs("span", { className: "text-gray-700 dark:text-gray-300", children: ["P\u00E1gina ", currentPage, " de ", totalPages] }), _jsx("button", { onClick: () => onPageChange(currentPage + 1), disabled: currentPage === totalPages, className: `px-4 py-2 rounded-md ${currentPage === totalPages
                            ? 'bg-gray-200 text-gray-400 cursor-not-allowed dark:bg-gray-700 dark:text-gray-500'
                            : 'bg-primary-500 text-white hover:bg-primary-600 dark:bg-primary-600 dark:hover:bg-primary-700'}`, children: "Siguiente" })] }))] }));
};
export default ResponsiveTable;
